"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Pencil, Plus, RefreshCw, Route, Save, ServerCog, Trash2, X } from "lucide-react";
import { api } from "@/lib/apiClient";
import { HTTP_SERVICE_TYPE_ID } from "@/lib/constants";
import { apiErrorMessage } from "@/lib/errors";
import type { Application, Service } from "@/lib/types";
import { Badge, Button, EmptyState, Feedback, Field, IconButton, Input, PageHeader, Select, Toggle } from "@/app/components/ui";

type FormState = { applicationId: string; serviceTypeId: string; path: string; targetHost: string; targetPort: string; active: boolean };
const emptyForm: FormState = { applicationId: "", serviceTypeId: HTTP_SERVICE_TYPE_ID, path: "/", targetHost: "", targetPort: "", active: true };

export default function ServicesPage() {
  const [items, setItems] = useState<Service[]>([]); const [applications, setApplications] = useState<Application[]>([]); const [form, setForm] = useState<FormState>(emptyForm); const [editingId, setEditingId] = useState(""); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const appById = useMemo(() => new Map(applications.map((item) => [item.id, item])), [applications]);
  const load = async () => { setLoading(true); setError(""); try { const [services, apps] = await Promise.all([api.get<Service[]>("/services", { params: { take: 100 } }), api.get<Application[]>("/applications", { params: { take: 100 } })]); setItems(services.data); setApplications(apps.data); } catch (err) { setError(apiErrorMessage(err, "Nao foi possivel carregar servicos.")); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const reset = () => { setEditingId(""); setForm(emptyForm); setFormOpen(false); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const payload = { ...form, targetPort: Number(form.targetPort) }; try { if (editingId) { await api.put(`/services/${editingId}`, payload); setMessage("Servico atualizado com sucesso."); } else { await api.post("/services", payload); setMessage("Servico criado com sucesso."); } reset(); await load(); } catch (err) { setError(apiErrorMessage(err, "Nao foi possivel salvar o servico.")); } finally { setSaving(false); } };
  const edit = (item: Service) => { setEditingId(item.id); setForm({ applicationId: item.applicationId, serviceTypeId: item.serviceTypeId, path: item.path, targetHost: item.targetHost, targetPort: String(item.targetPort), active: item.active }); setFormOpen(true); setMessage(""); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (id: string) => { if (!window.confirm("Excluir este servico?")) return; setMessage(""); setError(""); try { await api.delete(`/services/${id}`); setMessage("Servico removido."); await load(); } catch (err) { setError(apiErrorMessage(err, "Nao foi possivel remover o servico.")); } };

  return <div className="app-page">
    <PageHeader eyebrow="Roteamento" title="Servicos" description="Configure caminhos de entrada e os targets internos que processam cada requisicao." actions={<Button icon={<Plus size={16} />} onClick={() => { setFormOpen(true); setEditingId(""); setForm(emptyForm); }}>Novo servico</Button>} />
    <Feedback message={message} error={error} />
    {formOpen ? <form onSubmit={submit} className="panel"><div className="panel-header"><div><h2 className="panel-title">{editingId ? "Editar servico" : "Novo servico"}</h2><p className="panel-subtitle">Defina a rota publica e o destino na rede interna.</p></div><IconButton type="button" label="Fechar formulario" onClick={reset}><X size={17} /></IconButton></div><div className="panel-body">
      <div className="grid gap-5 lg:grid-cols-2"><Field label="Aplicacao"><Select value={form.applicationId} onChange={(e) => setForm({ ...form, applicationId: e.target.value })} required><option value="">Selecione uma aplicacao</option>{applications.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.slug})</option>)}</Select></Field><Field label="Path" hint="Caminho usado pelo gateway para localizar este servico."><Input value={form.path} placeholder="/api" onChange={(e) => setForm({ ...form, path: e.target.value })} required /></Field></div>
      <div className="mt-5 grid gap-5 md:grid-cols-[1fr_180px]"><Field label="Target host" hint="Hostname ou IP acessivel pela rede do gateway."><Input value={form.targetHost} placeholder="service.internal" onChange={(e) => setForm({ ...form, targetHost: e.target.value })} required /></Field><Field label="Target port"><Input type="number" min="1" max="65535" value={form.targetPort} placeholder="3000" onChange={(e) => setForm({ ...form, targetPort: e.target.value })} required /></Field></div>
      <div className="mt-5 grid items-end gap-5 border-t border-[var(--border)] pt-5 lg:grid-cols-[1fr_auto]"><Field label="Service type ID" hint="HTTP padrao seedado pela API; nao existe endpoint para listar tipos."><Input className="mono" value={form.serviceTypeId} onChange={(e) => setForm({ ...form, serviceTypeId: e.target.value })} required /></Field><Toggle checked={form.active} onChange={(active) => setForm({ ...form, active })} label="Servico ativo" /></div>
      <div className="mt-6 flex justify-end gap-2"><Button variant="secondary" type="button" onClick={reset}>Cancelar</Button><Button type="submit" disabled={saving} icon={<Save size={15} />}>{saving ? "Salvando..." : editingId ? "Salvar alteracoes" : "Criar servico"}</Button></div>
    </div></form> : null}
    <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="panel-title">Rotas configuradas</h2><p className="panel-subtitle">{items.filter((item) => item.active).length} de {items.length} servicos ativos</p></div><IconButton label="Atualizar lista" onClick={load} disabled={loading}><RefreshCw size={16} className={loading ? "animate-spin" : ""} /></IconButton></div>{items.length === 0 ? <EmptyState loading={loading} text="Nenhum servico cadastrado." /> : <div className="data-table-wrap"><table className="data-table min-w-[940px]"><thead><tr><th>Aplicacao</th><th>Rota</th><th>Target</th><th>Tipo</th><th>Status</th><th className="text-right">Acoes</th></tr></thead><tbody>{items.map((item) => { const app = appById.get(item.applicationId); return <tr key={item.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-[var(--warning-soft)] text-[var(--warning)]"><ServerCog size={17} /></span><div><p className="table-primary">{app?.name || "Aplicacao"}</p><p className="table-secondary">{app?.slug || item.applicationId.slice(0, 10)}</p></div></div></td><td><div className="flex items-center gap-2 font-medium"><Route size={14} className="text-[var(--muted)]" />{item.path}</div></td><td><p className="table-primary mono">{item.targetHost}:{item.targetPort}</p><p className="table-secondary">Destino interno</p></td><td><span className="rounded bg-[var(--panel-strong)] px-2 py-1 text-[10px] font-bold text-[var(--muted-strong)]">HTTP</span></td><td><Badge active={item.active} /></td><td><div className="table-actions"><IconButton label="Editar servico" onClick={() => edit(item)}><Pencil size={15} /></IconButton><IconButton label="Excluir servico" className="danger" onClick={() => remove(item.id)}><Trash2 size={15} /></IconButton></div></td></tr>; })}</tbody></table></div>}</section>
  </div>;
}
