"use client";

import { FormEvent, useState } from "react";
import { AppWindow, CheckCircle2, CornerDownRight, Globe2, Network, Play, Route, ServerCog, TriangleAlert } from "lucide-react";
import { api } from "@/lib/apiClient";
import { apiErrorMessage } from "@/lib/errors";
import type { ResolvedHost, ResolvedTarget } from "@/lib/types";
import { Badge, Button, Field, Input, PageHeader } from "@/app/components/ui";

export default function GatewayPage() {
  const [host, setHost] = useState(""); const [targetHost, setTargetHost] = useState(""); const [targetPath, setTargetPath] = useState("/"); const [hostResult, setHostResult] = useState<ResolvedHost | null>(null); const [targetResult, setTargetResult] = useState<ResolvedTarget | null>(null); const [hostError, setHostError] = useState(""); const [targetError, setTargetError] = useState(""); const [loadingHost, setLoadingHost] = useState(false); const [loadingTarget, setLoadingTarget] = useState(false);
  const resolveHost = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoadingHost(true); setHostError(""); setHostResult(null); try { const response = await api.get<ResolvedHost>(`/gateway/resolve-host/${encodeURIComponent(host)}`); setHostResult(response.data); } catch (err) { setHostError(apiErrorMessage(err, "Host nao resolvido.")); } finally { setLoadingHost(false); } };
  const resolveTarget = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoadingTarget(true); setTargetError(""); setTargetResult(null); try { const response = await api.get<ResolvedTarget>("/gateway/resolve", { params: { host: targetHost, path: targetPath } }); setTargetResult(response.data); } catch (err) { setTargetError(apiErrorMessage(err, "Target nao resolvido.")); } finally { setLoadingTarget(false); } };

  return <div className="app-page">
    <PageHeader eyebrow="Ferramentas" title="Diagnostico do gateway" description="Valide como um host e seu caminho sao interpretados pela configuracao atual." />
    <section className="grid gap-4 xl:grid-cols-2">
      <form onSubmit={resolveHost} className="panel"><div className="panel-header"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-[#eaf0f5] text-[#45667d] dark:bg-[#25323b] dark:text-[#91aabd]"><Globe2 size={18} /></span><div><h2 className="panel-title">Resolver host</h2><p className="panel-subtitle">Localize a aplicacao e todos os servicos associados.</p></div></div></div><div className="panel-body"><Field label="Host"><Input value={host} placeholder="api.exemplo.com" onChange={(e) => setHost(e.target.value)} required /></Field><Button className="mt-4" type="submit" disabled={loadingHost} icon={<Play size={14} />}>{loadingHost ? "Consultando..." : "Executar consulta"}</Button>{hostError ? <ErrorMessage text={hostError} /> : null}</div></form>
      <form onSubmit={resolveTarget} className="panel"><div className="panel-header"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-[var(--accent-soft)] text-[var(--accent)]"><Route size={18} /></span><div><h2 className="panel-title">Resolver destino</h2><p className="panel-subtitle">Descubra o target final de uma requisicao.</p></div></div></div><div className="panel-body"><div className="grid gap-4 sm:grid-cols-[1fr_150px]"><Field label="Host"><Input value={targetHost} placeholder="api.exemplo.com" onChange={(e) => setTargetHost(e.target.value)} required /></Field><Field label="Path"><Input value={targetPath} placeholder="/" onChange={(e) => setTargetPath(e.target.value)} required /></Field></div><Button className="mt-4" type="submit" disabled={loadingTarget} icon={<Play size={14} />}>{loadingTarget ? "Consultando..." : "Executar consulta"}</Button>{targetError ? <ErrorMessage text={targetError} /> : null}</div></form>
    </section>
    {!hostResult && !targetResult ? <section className="panel grid min-h-[260px] place-items-center p-8 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-md bg-[var(--panel-strong)] text-[var(--muted)]"><Network size={23} /></span><h2 className="mt-4 text-sm font-semibold">Aguardando diagnostico</h2><p className="mt-2 max-w-md text-xs leading-5 text-[var(--muted)]">Execute uma das consultas acima para visualizar a cadeia de resolucao produzida pela API.</p></div></section> : null}
    {hostResult ? <HostResult data={hostResult} /> : null}
    {targetResult ? <TargetResult data={targetResult} /> : null}
  </div>;
}

function ErrorMessage({ text }: { text: string }) { return <div className="feedback feedback-error mt-4"><TriangleAlert size={16} /><span>{text}</span></div>; }

function HostResult({ data }: { data: ResolvedHost }) {
  return <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="panel-title">Resultado do host</h2><p className="panel-subtitle">Cadeia encontrada para {data.host}</p></div><span className="badge badge-success"><CheckCircle2 size={12} />Resolvido</span></div><div className="panel-body"><div className="grid items-center gap-3 md:grid-cols-[1fr_auto_1fr]"><ResultNode icon={<Globe2 size={18} />} label="Dominio" primary={data.host} secondary={data.domainId} /><CornerDownRight className="mx-auto rotate-90 text-[var(--muted)] md:rotate-0" size={19} /><ResultNode icon={<AppWindow size={18} />} label="Aplicacao" primary={data.application.name} secondary={data.application.slug} /></div><div className="mt-5"><p className="mb-3 text-xs font-semibold text-[var(--muted-strong)]">Servicos disponiveis ({data.services.length})</p><div className="grid gap-2">{data.services.map((service) => <div key={service.id} className="flex flex-col justify-between gap-3 rounded-md border border-[var(--border)] bg-[var(--panel-soft)] p-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><ServerCog size={17} className="text-[var(--accent)]" /><div><p className="text-sm font-semibold">{service.path}</p><p className="mono mt-1 text-[var(--muted)]">{service.targetHost}:{service.targetPort}</p></div></div><Badge active={service.active} /></div>)}</div></div></div></section>;
}

function TargetResult({ data }: { data: ResolvedTarget }) {
  return <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="panel-title">Destino resolvido</h2><p className="panel-subtitle">Rota selecionada para {data.host}{data.path}</p></div><span className="badge badge-success"><CheckCircle2 size={12} />Resolvido</span></div><div className="panel-body"><div className="grid items-center gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr]"><ResultNode icon={<Globe2 size={18} />} label="Host" primary={data.host} secondary={data.domainId} /><CornerDownRight className="mx-auto rotate-90 text-[var(--muted)] md:rotate-0" size={18} /><ResultNode icon={<AppWindow size={18} />} label="Aplicacao" primary={data.application.name} secondary={data.application.slug} /><CornerDownRight className="mx-auto rotate-90 text-[var(--muted)] md:rotate-0" size={18} /><ResultNode icon={<ServerCog size={18} />} label="Target" primary={`${data.service.targetHost}:${data.service.targetPort}`} secondary={data.service.path} /></div></div></section>;
}

function ResultNode({ icon, label, primary, secondary }: { icon: React.ReactNode; label: string; primary: string; secondary: string }) { return <div className="min-w-0 rounded-md border border-[var(--border)] bg-[var(--panel-soft)] p-4"><span className="mb-3 grid h-8 w-8 place-items-center rounded-md bg-[var(--accent-soft)] text-[var(--accent)]">{icon}</span><p className="text-[10px] font-bold uppercase text-[var(--muted)]">{label}</p><p className="mt-1 truncate text-sm font-semibold">{primary}</p><p className="mono mt-1 truncate text-[var(--muted)]">{secondary}</p></div>; }
