"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ExternalLink, Globe2, Pencil, Plus, RefreshCw, Save, Trash2, X } from "lucide-react";
import { api } from "@/lib/apiClient";
import { apiErrorMessage } from "@/lib/errors";
import type { Application, Domain } from "@/lib/types";
import { Button, EmptyState, Feedback, Field, formatDate, IconButton, Input, PageHeader, Select } from "@/app/components/ui";

type FormState = { host: string; applicationId: string };
const emptyForm: FormState = { host: "", applicationId: "" };

export default function DomainsPage() {
  const [items, setItems] = useState<Domain[]>([]); const [applications, setApplications] = useState<Application[]>([]); const [form, setForm] = useState<FormState>(emptyForm);
  const [editingId, setEditingId] = useState(""); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const appById = useMemo(() => new Map(applications.map((item) => [item.id, item])), [applications]);
  const load = async () => { setLoading(true); setError(""); try { const [domains, apps] = await Promise.all([api.get<Domain[]>("/domains", { params: { take: 100 } }), api.get<Application[]>("/applications", { params: { take: 100 } })]); setItems(domains.data); setApplications(apps.data); } catch (err) { setError(apiErrorMessage(err, "Nao foi possivel carregar dominios.")); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const reset = () => { setEditingId(""); setForm(emptyForm); setFormOpen(false); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { if (editingId) { await api.put(`/domains/${editingId}`, form); setMessage("Dominio atualizado com sucesso."); } else { await api.post("/domains", form); setMessage("Dominio criado com sucesso."); } reset(); await load(); } catch (err) { setError(apiErrorMessage(err, "Nao foi possivel salvar o dominio.")); } finally { setSaving(false); } };
  const edit = (item: Domain) => { setEditingId(item.id); setForm({ host: item.host, applicationId: item.applicationId }); setFormOpen(true); setMessage(""); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (id: string) => { if (!window.confirm("Excluir este dominio?")) return; setMessage(""); setError(""); try { await api.delete(`/domains/${id}`); setMessage("Dominio removido."); await load(); } catch (err) { setError(apiErrorMessage(err, "Nao foi possivel remover o dominio.")); } };

  return <div className="app-page">
    <PageHeader eyebrow="Roteamento" title="Dominios" description="Associe hosts publicos as aplicacoes que recebem o trafego de entrada." actions={<Button icon={<Plus size={16} />} onClick={() => { setFormOpen(true); setEditingId(""); setForm(emptyForm); }}>Novo dominio</Button>} />
    <Feedback message={message} error={error} />
    {formOpen ? <form onSubmit={submit} className="panel"><div className="panel-header"><div><h2 className="panel-title">{editingId ? "Editar dominio" : "Novo dominio"}</h2><p className="panel-subtitle">Configure um host e sua aplicacao de destino.</p></div><IconButton type="button" label="Fechar formulario" onClick={reset}><X size={17} /></IconButton></div><div className="panel-body"><div className="grid gap-5 md:grid-cols-2"><Field label="Host" hint="Informe somente o host, sem protocolo ou caminho."><Input value={form.host} placeholder="api.exemplo.com" onChange={(e) => setForm({ ...form, host: e.target.value })} required autoFocus /></Field><Field label="Aplicacao" hint="Aplicacao que respondera por este host."><Select value={form.applicationId} onChange={(e) => setForm({ ...form, applicationId: e.target.value })} required><option value="">Selecione uma aplicacao</option>{applications.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.slug})</option>)}</Select></Field></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" type="button" onClick={reset}>Cancelar</Button><Button type="submit" disabled={saving} icon={<Save size={15} />}>{saving ? "Salvando..." : editingId ? "Salvar alteracoes" : "Criar dominio"}</Button></div></div></form> : null}
    <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="panel-title">Hosts mapeados</h2><p className="panel-subtitle">{items.length} dominios apontando para {new Set(items.map((item) => item.applicationId)).size} aplicacoes</p></div><IconButton label="Atualizar lista" onClick={load} disabled={loading}><RefreshCw size={16} className={loading ? "animate-spin" : ""} /></IconButton></div>{items.length === 0 ? <EmptyState loading={loading} text="Nenhum dominio cadastrado." /> : <div className="data-table-wrap"><table className="data-table min-w-[820px]"><thead><tr><th>Host</th><th>Aplicacao vinculada</th><th>Identificador</th><th>Criado em</th><th className="text-right">Acoes</th></tr></thead><tbody>{items.map((item) => { const app = appById.get(item.applicationId); return <tr key={item.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-[#eaf0f5] text-[#45667d] dark:bg-[#25323b] dark:text-[#91aabd]"><Globe2 size={17} /></span><div><p className="table-primary">{item.host}</p><p className="table-secondary flex items-center gap-1">HTTPS <ExternalLink size={10} /></p></div></div></td><td><p className="table-primary">{app?.name || "Aplicacao nao encontrada"}</p><p className="table-secondary">{app?.slug || "-"}</p></td><td className="mono text-[var(--muted)]">{item.applicationId.slice(0, 14)}</td><td className="text-[var(--muted)]">{formatDate(item.createdAt)}</td><td><div className="table-actions"><IconButton label="Editar dominio" onClick={() => edit(item)}><Pencil size={15} /></IconButton><IconButton label="Excluir dominio" className="danger" onClick={() => remove(item.id)}><Trash2 size={15} /></IconButton></div></td></tr>; })}</tbody></table></div>}</section>
  </div>;
}
